/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder8_15 (
    input [5:0] alufn,
    input [48:0] a,
    input [48:0] b,
    output reg [48:0] out,
    output reg z,
    output reg n,
    output reg v
  );
  
  
  
  reg [48:0] sum;
  
  reg [48:0] xb;
  
  always @* begin
    xb = b ^ {6'h31{alufn[0+0-:1]}};
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
      end
      2'h1: begin
        sum = a - b;
      end
      2'h2: begin
        sum = a * b;
      end
      default: begin
        sum = a - b;
      end
    endcase
    v = (a[48+0-:1] & xb[48+0-:1] & ~sum[48+0-:1]) | (~a[48+0-:1] & ~xb[48+0-:1] & sum[48+0-:1]);
    n = sum[48+0-:1];
    z = (~|sum);
    out = sum;
  end
endmodule
