/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module blinkingdecoder_14 (
    input [48:0] in,
    output reg [48:0] out
  );
  
  
  
  always @* begin
    out[0+6-:7] = in[0+6-:7];
    out[7+6-:7] = in[7+6-:7];
    out[14+6-:7] = in[14+6-:7];
    out[21+6-:7] = in[21+6-:7];
    out[28+6-:7] = in[28+6-:7];
    out[35+6-:7] = in[35+6-:7];
    out[42+6-:7] = in[42+6-:7];
  end
endmodule
