/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ledmatrixdecoder_12 (
    input [146:0] in,
    output reg [48:0] outred,
    output reg [48:0] outgreen,
    output reg [48:0] outblue
  );
  
  
  
  always @* begin
    outred[0+6-:7] = in[0+0+6-:7];
    outgreen[0+6-:7] = in[49+0+6-:7];
    outblue[0+6-:7] = in[98+0+6-:7];
    outred[7+6-:7] = in[0+7+6-:7];
    outgreen[7+6-:7] = in[49+7+6-:7];
    outblue[7+6-:7] = in[98+7+6-:7];
    outred[14+6-:7] = in[0+14+6-:7];
    outgreen[14+6-:7] = in[49+14+6-:7];
    outblue[14+6-:7] = in[98+14+6-:7];
    outred[21+6-:7] = in[0+21+6-:7];
    outgreen[21+6-:7] = in[49+21+6-:7];
    outblue[21+6-:7] = in[98+21+6-:7];
    outred[28+6-:7] = in[0+28+6-:7];
    outgreen[28+6-:7] = in[49+28+6-:7];
    outblue[28+6-:7] = in[98+28+6-:7];
    outred[35+6-:7] = in[0+35+6-:7];
    outgreen[35+6-:7] = in[49+35+6-:7];
    outblue[35+6-:7] = in[98+35+6-:7];
    outred[42+6-:7] = in[0+42+6-:7];
    outgreen[42+6-:7] = in[49+42+6-:7];
    outblue[42+6-:7] = in[98+42+6-:7];
  end
endmodule
