/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adjacencymat_35 (
    input clk,
    input rst,
    input [2:0] button,
    input player,
    input [48:0] currentstate,
    output reg [48:0] currentposition,
    output reg [48:0] adjmatrix
  );
  
  
  
  reg [48:0] M_current_d, M_current_q = 1'h0;
  localparam S3_state = 5'd0;
  localparam S4_state = 5'd1;
  localparam S5_state = 5'd2;
  localparam S11_state = 5'd3;
  localparam S15_state = 5'd4;
  localparam S18_state = 5'd5;
  localparam S21_state = 5'd6;
  localparam S22_state = 5'd7;
  localparam S23_state = 5'd8;
  localparam S24_state = 5'd9;
  localparam S25_state = 5'd10;
  localparam S26_state = 5'd11;
  localparam S27_state = 5'd12;
  localparam S28_state = 5'd13;
  localparam S29_state = 5'd14;
  localparam S32_state = 5'd15;
  localparam S35_state = 5'd16;
  localparam S39_state = 5'd17;
  localparam S45_state = 5'd18;
  localparam S46_state = 5'd19;
  localparam S47_state = 5'd20;
  
  reg [4:0] M_state_d, M_state_q = S3_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_current_d = M_current_q;
    
    if (currentstate == 49'h0000000000004) begin
      M_state_d = S3_state;
    end else begin
      if (currentstate == 49'h0000000000008) begin
        M_state_d = S4_state;
      end else begin
        if (currentstate == 49'h0000000000010) begin
          M_state_d = S5_state;
        end else begin
          if (currentstate == 49'h0000000000400) begin
            M_state_d = S11_state;
          end else begin
            if (currentstate == 49'h0000000004000) begin
              M_state_d = S15_state;
            end else begin
              if (currentstate == 49'h0000000020000) begin
                M_state_d = S18_state;
              end else begin
                if (currentstate == 49'h0000000100000) begin
                  M_state_d = S21_state;
                end else begin
                  if (currentstate == 49'h0000000200000) begin
                    M_state_d = S22_state;
                  end else begin
                    if (currentstate == 49'h0000000400000) begin
                      M_state_d = S23_state;
                    end else begin
                      if (currentstate == 49'h0000000800000) begin
                        M_state_d = S24_state;
                      end else begin
                        if (currentstate == 49'h0000001000000) begin
                          M_state_d = S25_state;
                        end else begin
                          if (currentstate == 49'h0000002000000) begin
                            M_state_d = S26_state;
                          end else begin
                            if (currentstate == 49'h0000004000000) begin
                              M_state_d = S27_state;
                            end else begin
                              if (currentstate == 49'h0000008000000) begin
                                M_state_d = S28_state;
                              end else begin
                                if (currentstate == 49'h0000010000000) begin
                                  M_state_d = S29_state;
                                end else begin
                                  if (currentstate == 49'h0000080000000) begin
                                    M_state_d = S32_state;
                                  end else begin
                                    if (currentstate == 49'h0000400000000) begin
                                      M_state_d = S35_state;
                                    end else begin
                                      if (currentstate == 49'h0004000000000) begin
                                        M_state_d = S39_state;
                                      end else begin
                                        if (currentstate == 49'h0100000000000) begin
                                          M_state_d = S45_state;
                                        end else begin
                                          if (currentstate == 49'h0200000000000) begin
                                            M_state_d = S46_state;
                                          end else begin
                                            if (currentstate == 49'h0400000000000) begin
                                              M_state_d = S47_state;
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    M_current_d = currentstate;
    
    case (M_state_q)
      S3_state: begin
        adjmatrix = 49'h0000000004408;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 4'h8;
          end else begin
            if (button == 3'h6) begin
              currentposition = M_current_q <<< 1'h1;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 4'hc;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 4'h8;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 4'hc;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S4_state: begin
        adjmatrix = 49'h0000000000414;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h6) begin
              currentposition = M_current_q <<< 1'h1;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S5_state: begin
        adjmatrix = 49'h0000000200408;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h6;
          end else begin
            if (button == 3'h6) begin
              currentposition = M_current_q <<< 5'h10;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h6;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 5'h10;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S11_state: begin
        adjmatrix = 49'h000000002001c;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q >>> 3'h6;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q >>> 4'h8;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q >>> 3'h6;
                end else begin
                  if (button == 3'h6) begin
                    currentposition = M_current_q >>> 4'h8;
                  end
                end
              end
            end
          end
        end
      end
      S15_state: begin
        adjmatrix = 49'h0000000600004;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 4'hc;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q <<< 4'h8;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 4'hc;
              end else begin
                if (button == 3'h7) begin
                  M_state_d = S23_state;
                  currentposition = M_current_q <<< 4'h8;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S18_state: begin
        adjmatrix = 49'h0000003800400;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q <<< 4'h8;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q <<< 3'h6;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q <<< 4'h8;
                end else begin
                  if (button == 3'h6) begin
                    currentposition = M_current_q <<< 3'h6;
                  end
                end
              end
            end
          end
        end
      end
      S21_state: begin
        adjmatrix = 49'h000000c000010;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 5'h10;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 3'h6;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 5'h10;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 3'h6;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S22_state: begin
        adjmatrix = 49'h0000010404000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q <<< 1'h1;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q <<< 1'h1;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S23_state: begin
        adjmatrix = 49'h0000010a04000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h6;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 4'h8;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 1'h1;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h6;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 4'h8;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q <<< 1'h1;
                end else begin
                  if (button == 3'h6) begin
                    currentposition = M_current_q >>> 1'h1;
                  end else begin
                    currentposition = M_current_q;
                  end
                end
              end
            end
          end
        end
      end
      S24_state: begin
        adjmatrix = 49'h0000081420000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 4'h8;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h6;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 1'h1;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 4'h8;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h6;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  if (button == 3'h7) begin
                    currentposition = M_current_q <<< 1'h1;
                  end
                end
              end
            end
          end
        end
      end
      S25_state: begin
        adjmatrix = 49'h0000082820000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 1'h1;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  if (button == 3'h7) begin
                    currentposition = M_current_q <<< 1'h1;
                  end
                end
              end
            end
          end
        end
      end
      S26_state: begin
        adjmatrix = 49'h0000085020000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h6;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 4'h8;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 1'h1;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h6;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 4'h8;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  if (button == 3'h7) begin
                    currentposition = M_current_q <<< 1'h1;
                  end
                end
              end
            end
          end
        end
      end
      S27_state: begin
        adjmatrix = 49'h000040a100000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 4'h8;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h6;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q <<< 1'h1;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 4'h8;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h6;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  if (button == 3'h7) begin
                    currentposition = M_current_q <<< 1'h1;
                  end
                end
              end
            end
          end
        end
      end
      S28_state: begin
        adjmatrix = 49'h0000404100000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S29_state: begin
        adjmatrix = 49'h0000010600000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 5'h10;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q >>> 3'h6;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 5'h10;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q >>> 3'h6;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S32_state: begin
        adjmatrix = 49'h0002003800000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q >>> 3'h6;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q >>> 4'h8;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q >>> 3'h6;
                end else begin
                  if (button == 3'h6) begin
                    currentposition = M_current_q >>> 4'h8;
                  end
                end
              end
            end
          end
        end
      end
      S35_state: begin
        adjmatrix = 49'h040000c000000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 4'hc;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 4'h8;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 4'hc;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 4'h8;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S39_state: begin
        adjmatrix = 49'h0700080000000;
        if (player == 1'h0) begin
          if (button == 3'h1) begin
            currentposition = M_current_q <<< 3'h7;
          end else begin
            if (button == 3'h2) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h6) begin
                currentposition = M_current_q <<< 4'h8;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q <<< 3'h6;
                end
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h2) begin
              currentposition = M_current_q <<< 3'h7;
            end else begin
              if (button == 3'h1) begin
                currentposition = M_current_q >>> 3'h7;
              end else begin
                if (button == 3'h7) begin
                  currentposition = M_current_q <<< 4'h8;
                end else begin
                  if (button == 3'h6) begin
                    currentposition = M_current_q <<< 3'h6;
                  end
                end
              end
            end
          end
        end
      end
      S45_state: begin
        adjmatrix = 49'h0204010000000;
        if (player == 1'h0) begin
          if (button == 3'h2) begin
            currentposition = M_current_q >>> 3'h6;
          end else begin
            if (button == 3'h6) begin
              currentposition = M_current_q <<< 1'h1;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 5'h10;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h1) begin
              currentposition = M_current_q >>> 3'h6;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 5'h10;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S46_state: begin
        adjmatrix = 49'h0504000000000;
        if (player == 1'h0) begin
          if (button == 3'h2) begin
            currentposition = M_current_q >>> 3'h7;
          end else begin
            if (button == 3'h6) begin
              currentposition = M_current_q <<< 1'h1;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h1) begin
              currentposition = M_current_q >>> 3'h7;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q <<< 1'h1;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      S47_state: begin
        adjmatrix = 49'h0204400000000;
        if (player == 1'h0) begin
          if (button == 3'h2) begin
            currentposition = M_current_q >>> 4'h8;
          end else begin
            if (button == 3'h6) begin
              currentposition = M_current_q >>> 4'hc;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 1'h1;
              end else begin
                currentposition = M_current_q;
              end
            end
          end
        end else begin
          if (player == 1'h1) begin
            if (button == 3'h1) begin
              currentposition = M_current_q >>> 4'h8;
            end else begin
              if (button == 3'h7) begin
                currentposition = M_current_q >>> 4'hc;
              end else begin
                if (button == 3'h6) begin
                  currentposition = M_current_q >>> 1'h1;
                end else begin
                  currentposition = M_current_q;
                end
              end
            end
          end
        end
      end
      default: begin
        adjmatrix = 49'h0000000000000;
        currentposition = 49'h0000000000000;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_current_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_current_q <= M_current_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
