/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lightupbeforemove_32 (
    input clk,
    input rst,
    input [48:0] selectedposition,
    input [48:0] player1,
    input [48:0] player2,
    input player,
    output reg [48:0] positionstolightup
  );
  
  
  
  wire [49-1:0] M_adjacencymat_currentposition;
  wire [49-1:0] M_adjacencymat_adjmatrix;
  reg [3-1:0] M_adjacencymat_button;
  reg [1-1:0] M_adjacencymat_player;
  reg [49-1:0] M_adjacencymat_currentstate;
  adjacencymat_30 adjacencymat (
    .clk(clk),
    .rst(rst),
    .button(M_adjacencymat_button),
    .player(M_adjacencymat_player),
    .currentstate(M_adjacencymat_currentstate),
    .currentposition(M_adjacencymat_currentposition),
    .adjmatrix(M_adjacencymat_adjmatrix)
  );
  
  always @* begin
    M_adjacencymat_player = player;
    M_adjacencymat_button = 1'h0;
    M_adjacencymat_currentstate = selectedposition;
    positionstolightup = ~(player1 | player2) & M_adjacencymat_adjmatrix;
  end
endmodule
