/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module move_6 (
    input clk,
    input rst,
    input [48:0] selectedpositionfromselect,
    input [48:0] player1,
    input [48:0] player2,
    input player,
    input [2:0] buttons,
    output reg [48:0] positionmovedto,
    output reg movesuccess,
    output reg [48:0] player1moved,
    output reg [48:0] player2moved,
    output reg [48:0] lightupbeforemovepos
  );
  
  
  
  wire [49-1:0] M_adjacencymat_currentposition;
  wire [49-1:0] M_adjacencymat_adjmatrix;
  reg [3-1:0] M_adjacencymat_button;
  reg [1-1:0] M_adjacencymat_player;
  reg [49-1:0] M_adjacencymat_currentstate;
  adjacencymat_35 adjacencymat (
    .clk(clk),
    .rst(rst),
    .button(M_adjacencymat_button),
    .player(M_adjacencymat_player),
    .currentstate(M_adjacencymat_currentstate),
    .currentposition(M_adjacencymat_currentposition),
    .adjmatrix(M_adjacencymat_adjmatrix)
  );
  
  wire [49-1:0] M_lightupbeforemove_positionstolightup;
  reg [49-1:0] M_lightupbeforemove_selectedposition;
  reg [49-1:0] M_lightupbeforemove_player1;
  reg [49-1:0] M_lightupbeforemove_player2;
  reg [1-1:0] M_lightupbeforemove_player;
  lightupbeforemove_37 lightupbeforemove (
    .clk(clk),
    .rst(rst),
    .selectedposition(M_lightupbeforemove_selectedposition),
    .player1(M_lightupbeforemove_player1),
    .player2(M_lightupbeforemove_player2),
    .player(M_lightupbeforemove_player),
    .positionstolightup(M_lightupbeforemove_positionstolightup)
  );
  
  reg [48:0] selectedpositiontomoveto;
  
  always @* begin
    player1moved = player1;
    player2moved = player2;
    movesuccess = 1'h0;
    positionmovedto = selectedpositionfromselect;
    M_adjacencymat_player = player;
    M_adjacencymat_button = buttons;
    M_adjacencymat_currentstate = selectedpositionfromselect;
    M_lightupbeforemove_player1 = player1;
    M_lightupbeforemove_player2 = player2;
    M_lightupbeforemove_selectedposition = selectedpositionfromselect;
    M_lightupbeforemove_player = player;
    lightupbeforemovepos = M_lightupbeforemove_positionstolightup;
    selectedpositiontomoveto = M_adjacencymat_currentposition;
    if ((|(selectedpositiontomoveto & M_lightupbeforemove_positionstolightup)) == 1'h1) begin
      movesuccess = 1'h1;
      positionmovedto = selectedpositiontomoveto;
    end
    if (player == 1'h0) begin
      player1moved = selectedpositiontomoveto | (~selectedpositionfromselect) & player1;
    end else begin
      if (player == 1'h1) begin
        player2moved = selectedpositiontomoveto | (~selectedpositionfromselect) & player2;
      end
    end
  end
endmodule
