/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module select_5 (
    input clk,
    input rst,
    input [48:0] player1,
    input [48:0] player2,
    input [48:0] cursor,
    input [2:0] button,
    input player,
    output reg successfulselect,
    output reg [48:0] currentposition
  );
  
  
  
  reg [48:0] overall;
  
  reg [48:0] check;
  
  reg [48:0] overallandadj;
  
  reg [48:0] newoverallandadj;
  
  wire [49-1:0] M_adjacencymat_currentposition;
  wire [49-1:0] M_adjacencymat_adjmatrix;
  reg [3-1:0] M_adjacencymat_button;
  reg [1-1:0] M_adjacencymat_player;
  reg [49-1:0] M_adjacencymat_currentstate;
  adjacencymat_35 adjacencymat (
    .clk(clk),
    .rst(rst),
    .button(M_adjacencymat_button),
    .player(M_adjacencymat_player),
    .currentstate(M_adjacencymat_currentstate),
    .currentposition(M_adjacencymat_currentposition),
    .adjmatrix(M_adjacencymat_adjmatrix)
  );
  
  always @* begin
    successfulselect = 1'h0;
    check = 49'h0000000000000;
    M_adjacencymat_button = button;
    M_adjacencymat_player = player;
    overall = player1 | player2;
    if (player == 1'h0) begin
      M_adjacencymat_player = 1'h0;
      check = player1 & cursor;
    end else begin
      if (player == 1'h1) begin
        M_adjacencymat_player = 1'h1;
        check = player2 & cursor;
      end
    end
    M_adjacencymat_currentstate = cursor;
    if (check != 49'h0000000000000) begin
      overallandadj = M_adjacencymat_adjmatrix & overall;
      newoverallandadj = overallandadj ^ M_adjacencymat_adjmatrix;
      if (newoverallandadj != 49'h0000000000000) begin
        successfulselect = 1'h1;
      end
    end
    currentposition = M_adjacencymat_currentposition;
  end
endmodule
