/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module start_4 (
    output reg [48:0] player1,
    output reg [48:0] player2
  );
  
  
  
  localparam PLAYER1 = 49'h0100010604004;
  
  localparam PLAYER2 = 49'h040040c100010;
  
  always @* begin
    player1 = 49'h0100010604004;
    player2 = 49'h040040c100010;
  end
endmodule
